---
- name: Configure favorite-apps
  ansible.legacy.dconf:  # noqa: fqcn[canonical]
    key: /org/gnome/shell/favorite-apps
    value: "['org.gnome.Nautilus.desktop']"
    state: present

- name: Configure background
  ansible.legacy.dconf:  # noqa: fqcn[canonical]
    key: /org/gnome/desktop/background/{{ item.key }}
    value: "{{ item.value }}"
    state: present
  loop:
    - {key: picture-options, value: "'none'"}
    - {key: primary-color, value: "'#000000'"}
    - {key: secondary-color, value: "'#000000'"}

- name: Configure GNOME
  ansible.legacy.dconf:  # noqa: fqcn[canonical]
    key: /org/gnome/{{ item.key }}
    value: "{{ item.value | string }}"
    state: present
  loop: "{{ desktop_gnome_configuration }}"

- name: Creaet extensions dir
  ansible.builtin.file:
    dest: "{{ ansible_env['HOME'] }}/.local/share/gnome-shell/extensions/switch-keyboard-layout@ansible"
    state: directory
    mode: '0750'

- name: Copy extension file
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env['HOME'] }}/.local/share/gnome-shell/extensions/switch-keyboard-layout@ansible"
    mode: '0640'
  loop:
    - extension.js
    - metadata.json

- name: Configure GNOME Terminal keybinding
  ansible.legacy.dconf:  # noqa: fqcn[canonical]
    key: "/org/gnome/terminal/legacy/keybindings/{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - {key: copy, value: "'<Primary>c'"}
    - {key: paste, value: "'<Primary>v'"}

- name: Configure GNOME Terminal
  ansible.legacy.dconf:  # noqa: fqcn[canonical]
    key: "/org/gnome/terminal/legacy/profiles:/{{ desktop_terminal_profiles }}/{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - {key: audible-bell, value: "false"}
    - {key: background-color, value: "'rgb(0,0,0)'"}
    - {key: foreground-color, value: "'rgb(255,255,255)'"}
    - {key: use-theme-colors, value: "false"}
    - {key: visible-name, value: "'{{ ansible_env['USER'] }}'"}

- name: Check NerdFonts
  ansible.builtin.stat:
    path: "{{ ansible_env['HOME'] }}/.local/share/fonts/NerdFonts"
  register: source_code_pro

- name: Install NerdFonts
  when: not source_code_pro.stat.exists
  block:
    - name: Download NerdFonts
      ansible.builtin.git:
        repo: https://github.com/ryanoasis/nerd-fonts.git
        dest: "{{ ansible_env['HOME'] }}/.nerd-fonts"
        version: master
        depth: 1

    - name: Install
      ansible.builtin.command: "{{ ansible_env['HOME'] }}/.nerd-fonts/install.sh"
      changed_when: False

- name: Configure GNOME Terminal fonts
  ansible.legacy.dconf:  # noqa: fqcn[canonical]
    key: "/org/gnome/terminal/legacy/profiles:/{{ desktop_terminal_profiles }}/{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - {key: font, value: "'SauceCodePro Nerd Font Medium 11'"}
    - {key: use-system-font, value: "false"}

- name: Configure hidden files
  ansible.builtin.blockinfile:
    path: "{{ ansible_env['HOME'] }}/.hidden"
    block: "{{ desktop_hidden }}"
    create: true
    mode: '0640'
  tags: hidden

- name: Configure bookmarks
  ansible.builtin.copy:
    dest: "{{ ansible_env['HOME'] }}/.config/gtk-3.0/bookmarks"
    content: "{{ desktop_bookmarks }}"
    mode: '0664'
  tags: bookmarks

- name: Add shortcuts
  ansible.builtin.include_tasks:
    file: add_shortcut.yml
    apply:
      tags: shortcuts
  loop: "{{ desktop_shortcuts }}"
  loop_control:
    loop_var: key
  tags: shortcuts

- name: Create custom-keybindings key
  ansible.builtin.set_fact:
    custom_keybindings: >-
      {{ custom_keybindings | default([]) +
      ['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/' + item.key + '/'] }}
  loop: "{{ desktop_shortcuts }}"
  tags: shortcuts

- name: Configure custom-keybindings
  ansible.legacy.dconf:  # noqa: fqcn[canonical]
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "{{ custom_keybindings }}"
    state: present
  tags: shortcuts

- name: Logitech hwdb configure
  ansible.builtin.copy:
    content: |-
      evdev:name:Logitech USB Receiver Mouse:*
       ID_INPUT_KEY=1
       KEYBOARD_KEY_90006=leftmeta
    dest: /etc/udev/hwdb.d/61-keyboard-local.hwdb
    mode: '0644'
    owner: root
    group: root
  notify: Logitech update hwdb
  become: True
  tags: logitech
  when: desktop_logitech | bool
