---
- name: Install Docker prerequisites
  ansible.builtin.apt:
    name:
      - apt-transport-https

- name: Get stats of Docker key
  ansible.builtin.stat:
    path: "{{ docker_key }}"
  register: result

- name: Install Docker key
  when: not result.stat.exists
  block:
    - name: Download Docker key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: "{{ docker_armored_key }}"
        mode: '0664'

    - name: Dearmor docker.asc
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          cat "{{ docker_armored_key }}" | gpg --dearmor > "{{ docker_key }}"
        creates: "{{ docker_key }}"
        executable: /bin/bash

    - name: Remove {{ docker_armored_key }}
      ansible.builtin.file:
        path: "{{ docker_armored_key }}"
        state: absent

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64 signed-by={{ docker_key }}]
      https://download.docker.com/linux/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} stable

- name: Install Docker
  ansible.builtin.apt:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
    update_cache: "yes"

- name: Add to the docker group
  ansible.builtin.user:
    name: "{{ ansible_env['USER'] }}"
    groups: docker
    append: "yes"

- name: Pull images
  community.docker.docker_image:
    name: "{{ item }}"
    source: pull
  loop: "{{ docker_images }}"
